#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/Box2 ./files/Box2/etc/scripts/init
  cp ./scripts/RouteurFAI ./files/RouteurFAI/etc/scripts/init
  cp ./scripts/Routeur1 ./files/Routeur1/etc/scripts/init
  cp ./scripts/Box1 ./files/Box1/etc/scripts/init
  cp ./scripts/Routeur2 ./files/Routeur2/etc/scripts/init
  cp ./scripts/RouteurService ./files/RouteurService/etc/scripts/init
  cp ./scripts/RouteurServiceReseau ./files/RouteurServiceReseau/etc/scripts/init
  cp ./scripts/ServeurWebUtilisateur ./files/ServeurWebUtilisateur/var/scripts/init
  cp ./scripts/ServeurWeb ./files/ServeurWeb/var/scripts/init
  cp ./scripts/ServeurDns ./files/ServeurDns/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
