#!/bin/bash 
ip link set dev eth0 up
ip a a 192.168.84.1/25 dev eth0
ip link set dev eth1 up
ip a a 45.8.75.2/27 dev eth1
ip route add default via 45.8.75.1
#echo 1 >/proc/sys/net/ipv4/ip_forward
service isc-dhcp-server restart
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

# Cacher les adresses ip des paquets sortants et afficher celle de la box a la place
iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 45.8.75.2

# Parametrage de la table pour refuser tout paquet entrant
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Autorisation des pings
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# Autoriser le protocole RIP
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

# Autoriser le service DNS
iptables -t filter -A FORWARD -d 45.8.75.98/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 45.8.75.98/27 -p udp --sport 53 -j ACCEPT

# Autoriser le service WEB
iptables -t filter -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 80 -j ACCEPT
