#!/bin/bash

# Mise en marche des ports
ip link set dev eth0 up
ip link set dev eth1 up

# On ajoute les ip aux ports
ip a a 45.8.75.130/27 dev eth0
ip a a 192.168.84.1/25 dev eth1

# Ajout de la route par defaut
ip route add default via 45.8.75.129

# Activation du routage
echo 1 >/proc/sys/net/ipv4/ip_forward

# Lancement du dhcp
service isc-dhcp-server restart

# Pour pouvoir ping a l'interieur dureseau prive
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# Cacher les adresses ip des paquets sortants et afficher celle de la box a la place
iptables -t nat -A POSTROUTING -o eth1 -j SNAT --to-source 45.8.75.130

# Parametrage de la table pour refuser tout paquet entrant
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Autorisation des pings
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# Autoriser le protocole RIP
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

# Autoriser le service DNS
iptables -t filter -A FORWARD -d 45.8.75.98/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 45.8.75.98/27 -p udp --sport 53 -j ACCEPT

# Autoriser le WEB
iptables -t filter -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 80 -j ACCEPT

# Changer d'adresse de destination en arrivant sur Box2 pour atteindre le serveur WEB utilisateur.
iptables -t nat -A PREROUTING -p tcp -d 45.8.75.130 --dport 80 -j DNAT --to-destination 192.168.84.2

