#!/bin/bash
ip link set dev eth0 up
ip a a 45.8.75.34/27 dev eth0
ip link set dev eth1 up
ip a a 45.8.75.97/27 dev eth1
ip link set dev eth2 up
ip a a 45.8.75.162/27 dev eth2

# Parametrage de la table pour refuser tout paquet entrant
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Autorisation des pings
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# Autoriser le protocole RIP
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

# Autoriser le service DNS
iptables -t filter -A FORWARD -d 45.8.75.98/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 45.8.75.98/27 -p udp --sport 53 -j ACCEPT

# Autoriser le service WEB
iptables -t filter -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 80 -j ACCEPT
