#!/bin/bash
ip link set dev eth0 up
ip a a 45.5.77.130/27 dev eth0

ip link set dev eth1 up
ip a a 45.5.77.162/27 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start
(echo "zebra"; echo "en"; echo "conf t"; echo "router rip"; echo "network 45.5.77.128/27"; echo "network 45.5.77.160/27") | (telnet localhost ripd)
