#!/bin/bash
ip link set dev eth0 up
ip a a 45.5.77.163/27 dev eth0

ip link set dev eth1 up
ip a a 45.5.77.209/28 dev eth1

ip link set dev eth2 up
ip a a 45.5.77.193/28 dev eth2

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start
(echo "zebra"; echo "en"; echo "conf t"; echo "router rip"; echo "network 45.5.77.208/28"; echo "network 45.5.77.160/27" ; echo "network 45.5.77.192/28") | (telnet localhost ripd)
